Name: Python application test MicroServices with github actions
on: [push]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    -uses: Action/
    -name: set up Python.3.10
    uses: actions/setup-python@v3
    with
      python-version: 3.10
    -name: Install dependencies
    run: |
      make install
    -name: Lint with pylint
    run: |
      #make lint
    -name: Test with pytest
    run: |
      #make test
    -name : Format code
    run: |
      #make format 
